
SET SERVEROUT ON

DROP PROCEDURE CREATE_TABLE_IF_DOESNT_EXIT;

CREATE OR REPLACE PROCEDURE CREATE_TABLE_IF_DOESNT_EXIT(
  TABLENAME VARCHAR2,
  QUERY VARCHAR2
)
IS N NUMBER;
BEGIN
  SELECT COUNT(*) INTO N FROM USER_TABLES WHERE TABLE_NAME = UPPER(TABLENAME);
  IF (N = 0) THEN
    EXECUTE IMMEDIATE QUERY;
  END IF;
END;

--테스트용
EXEC CREATE_TABLE_IF_DOESNT_EXIT('TTSS', 'CREATE TABLE TTSS (ID NUMBER)');
SELECT COUNT(*) INTO N FROM USER_TABLES WHERE TABLE_NAME = UPPER('TTSS');
INSERT INTO MEMBER(MEMBER_ID) VALUES(10);
DROP TABLE MEMBER;
SELECT* FROM MEMBER;